DELIMITER $$

USE BDPOKEMON$$

DROP FUNCTION IF EXISTS FN_GET_ID_POKEMON$$
CREATE FUNCTION FN_GET_ID_POKEMON(NOMBRE_POKEMON VARCHAR(20))
RETURNS INT UNSIGNED
READS SQL DATA
BEGIN
	RETURN	(
				SELECT ID 
					FROM POKEMONS
					WHERE NOMBRE = NOMBRE_POKEMON
            );
END$$

DROP FUNCTION IF EXISTS FN_GET_NOMBRE_POKEMON$$
CREATE FUNCTION FN_GET_NOMBRE_POKEMON(ID_POKEMON INT UNSIGNED)
RETURNS VARCHAR(20)
READS SQL DATA
BEGIN
	RETURN	(
				SELECT NOMBRE
					FROM POKEMONS
                    WHERE ID = ID_POKEMON
            );
END$$

DROP FUNCTION IF EXISTS FN_GET_ID_RUTA$$
CREATE FUNCTION  FN_GET_ID_RUTA(NOMBRE_RUTA VARCHAR(50), REGION_RUTA VARCHAR(20))
RETURNS INT UNSIGNED
READS SQL DATA
BEGIN
	RETURN 	(
				SELECT ID
					FROM RUTAS
                    WHERE NOMBRE = NOMBRE_RUTA
						AND
					REGION = REGION_RUTA
            );
END$$

